#!/usr/bin/env python3
"""
find_dead_code.py — Find unused definitions and lemmata in Rocq (.v) files.

Uses .glob files produced by rocqc for exact, name-resolved dead-code
detection.  Unlike a text/regex search, .glob files carry the fully-
qualified library path for every reference, so two modules that happen
to define an identically-named entity are tracked independently.

Algorithm
---------
1. For each source file listed in _CoqProject, read the corresponding
   .glob file (generated by a prior `make` run).
2. From each .glob file collect:
     • tracked *definitions*  (glob record kinds: def, prf)
     • *references*  (R lines) — each records the byte offset of a use
       site together with the fully-qualified name of the entity it refers to.
3. Build a uses-graph by mapping every reference to the definition that
   lexically contains it: the tracked definition whose name byte-offset is
   the largest offset ≤ the reference's byte offset.
4. *Live roots* = names in the allowlist  +  definitions referenced from
   text before the first tracked definition in their file (Require / Import
   preambles, top-level commands outside any definition body).
5. BFS from live roots through the uses-graph; every definition not
   reachable from any live root is reported as dead.

.glob file format (relevant lines)
-----------------------------------
  Line 1:  DIGEST <hash>
  Line 2:  F<FullyQualifiedLibraryPath>    e.g. FLocalMech.LoCalSafety

  Definition records (tracked kinds only):
    def <start>:<end> <ShortModule> <name>
    prf <start>:<end> <ShortModule> <name>
    (<start> and <end> are byte offsets of the identifier in the .v file)

  Reference records:
    R<start>:<end> <FullLibPath> <ShortModule> <name>[:<idx>] <kind>
    • <FullLibPath> identifies the module that defines the name
    • <ShortModule> is <> for intra-file or anonymous (index-style) references
    • <name> may carry a :<idx> suffix for by-index references; strip it

Why only def / prf?
  ind / constr (inductives & constructors) are almost always referenced in
  type annotations and generate noisy false positives.  scheme entries are
  auto-generated.  abbrev / proj / class are too specialised to analyse
  without additional context.

Usage
-----
    python3 scripts/find_dead_code.py [--coqproject _CoqProject]
                                       [--allowlist FILE]
                                       [--error-on-dead]
                                       [--verbose]

Allowlist file format
---------------------
  One bare name per line.  Lines starting with '#' and blank lines are
  ignored.  Names listed here are always treated as live.

Exit codes
----------
  0  — no (non-allowlisted) dead definitions found
  1  — dead definitions found AND --error-on-dead was passed
  2  — usage / file error
"""

import sys
import bisect
import argparse
import re
from pathlib import Path


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Only these glob record kinds are tracked as user-defined, analysable entities.
TRACKED_KINDS = frozenset({"def", "prf"})

# Regex for definition-record lines:
#   <kind> <start>:<end_ignored> <ShortModule> <name>
_DEF_RE = re.compile(r"^(def|prf) (\d+):\d+ \S+ (\S+)$")

# Regex for reference lines — we capture start, lib-path, raw name AND ref-kind:
#   R<start>:<end_ignored> <FullLibPath> <ShortModule_ignored> <raw_name> <ref_kind>
_REF_RE = re.compile(r"^R(\d+):\d+ (\S+) \S+ (\S+) (\S+)$")

# Regex for mutual-Lemma with-clauses in .v source:
#   "with <name> :" (colon then whitespace/newline) but NOT ":=" (Fixpoint/Scheme/Inductive).
# This pattern marks the second component of a "Lemma A ... with B : ..." proof.
_MUTUAL_LEMMA_WITH_RE = re.compile(
    r"^\s*with\s+([A-Za-z_][A-Za-z0-9_']*)\s*:(?!=)",
    re.MULTILINE,
)

# Regex for mutual-Definition with-clauses in .v source (Scheme / Fixpoint / CoFixpoint):
#   "with <name> :=" at the start of a line.
# The secondary component of "Scheme A := ... with B := ..." needs this edge so
# that if A is live (e.g. used in a Combined Scheme), B is also live — even when
# the Combined Scheme omits B.  For mutual Fixpoints the cross-references already
# appear as R-lines in the glob; the extra edge is harmless.
_MUTUAL_DEF_WITH_RE = re.compile(
    r"^\s*with\s+([A-Za-z_][A-Za-z0-9_']*)\s*:=",
    re.MULTILINE,
)

# Display labels for output.
_KIND_LABEL: dict[str, str] = {"def": "Definition", "prf": "Lemma"}

# Type alias: a definition is keyed by (full_lib_path, bare_name).
# Using the full lib path means A.f and B.f are distinct keys even if the
# bare name "f" appears in both modules.
DefKey = tuple[str, str]


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------

def _byte_to_line(text: str, pos: int) -> int:
    """Return the 1-based line number for byte offset *pos* in *text*."""
    return text[:pos].count("\n") + 1


def read_coqproject(coqproject_path: Path) -> list[Path]:
    """Return the list of .v source files from a _CoqProject file."""
    base = coqproject_path.parent
    files: list[Path] = []
    with open(coqproject_path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line.endswith(".v") and not line.startswith("-"):
                files.append(base / line)
    return files


def read_allowlist(path: Path) -> set[str]:
    """Read a bare-name-per-line allowlist; ignore blank lines and comments."""
    allowed: set[str] = set()
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            name = line.split("#", 1)[0].strip()
            if name:
                allowed.add(name)
    return allowed


# ---------------------------------------------------------------------------
# .glob parsing
# ---------------------------------------------------------------------------

def parse_glob(
    glob_path: Path,
    v_text: str,
) -> tuple[
    str,                                    # full_lib_path  e.g. "LocalMech.LoCalSafety"
    list[tuple[int, int, str, str]],        # defs: (byte_offset, line_no, name, kind)
    list[tuple[int, str, str, str]],        # refs: (byte_offset, full_lib_path, bare_name, ref_kind)
]:
    """
    Parse *glob_path* and return (full_lib_path, defs, refs).

    *v_text* is the content of the corresponding .v file; it is used only to
    convert byte offsets to 1-based line numbers for human-readable output.

    Definitions are returned sorted by byte offset so callers can use
    binary search to find the definition that contains a given reference.
    """
    full_lib_path = ""
    defs: list[tuple[int, int, str, str]] = []
    refs: list[tuple[int, str, str, str]] = []

    with open(glob_path, encoding="utf-8", errors="replace") as fh:
        for i, raw in enumerate(fh):
            line = raw.rstrip("\n")

            if i == 0:
                continue  # DIGEST line — not needed

            if i == 1:
                # "FLocalMech.LoCalSafety" → "LocalMech.LoCalSafety"
                if line.startswith("F"):
                    full_lib_path = line[1:]
                continue

            m = _DEF_RE.match(line)
            if m:
                kind, start_s, name = m.groups()
                start = int(start_s)
                defs.append((start, _byte_to_line(v_text, start), name, kind))
                continue

            m = _REF_RE.match(line)
            if m:
                start_s, lib, raw_name, ref_kind = m.groups()
                # Strip by-index suffix: "expr_bound_term_vars:119" → "expr_bound_term_vars"
                # Also skip pure-placeholder names like "<>".
                bare = raw_name.split(":")[0]
                if bare and bare != "<>":
                    refs.append((int(start_s), lib, bare, ref_kind))

    defs.sort(key=lambda d: d[0])
    return full_lib_path, defs, refs


# ---------------------------------------------------------------------------
# Core analysis
# ---------------------------------------------------------------------------

def find_dead_code(
    coqproject: Path,
    verbose: bool = False,
    allowlist: set[str] | None = None,
) -> list[tuple[str, int, str, str]]:
    """
    Analyse all .v files listed in *coqproject* (via their .glob files) and
    return a list of dead definitions as (v_filename, line_no, kind, name).

    Requires a recent successful build so that .glob files exist and match
    the current source.  Names in *allowlist* are always considered live.
    """
    if allowlist is None:
        allowlist = set()

    source_files = read_coqproject(coqproject)

    # Per-library data used during graph construction.
    #   lib_path → (defs_sorted_by_byte, refs)
    file_data: dict[str, tuple[
        list[tuple[int, int, str, str]],   # defs
        list[tuple[int, str, str, str]],   # refs  (byte, lib, name, ref_kind)
    ]] = {}

    # Global definition registry: DefKey → (v_filename, line_no, kind)
    registry: dict[DefKey, tuple[str, int, str]] = {}

    # Full lib paths that belong to this project (used to filter refs).
    local_libs: set[str] = set()

    # Per-lib mapping: name → v_text (needed for mutual-lemma scan)
    v_texts: dict[str, str] = {}

    for v_path in source_files:
        glob_path = v_path.with_suffix(".glob")

        if not v_path.exists():
            print(f"Warning: {v_path} not found", file=sys.stderr)
            continue
        if not glob_path.exists():
            print(
                f"Warning: {glob_path} not found — run 'make' first",
                file=sys.stderr,
            )
            continue

        v_text = v_path.read_text(encoding="utf-8")
        lib_path, defs, refs = parse_glob(glob_path, v_text)

        if not lib_path:
            print(f"Warning: no F-line found in {glob_path}", file=sys.stderr)
            continue

        local_libs.add(lib_path)
        file_data[lib_path] = (defs, refs)
        v_texts[lib_path] = v_text

        fname = v_path.name
        for _byte, line_no, name, kind in defs:
            key: DefKey = (lib_path, name)
            registry[key] = (fname, line_no, kind)

    # Resolve allowlist bare names to DefKeys.
    # A bare name matches any local definition with that name, regardless of
    # which module it lives in (names in the allowlist are project-wide).
    allowlisted: set[DefKey] = {
        (lib, name)
        for (lib, name) in registry
        if name in allowlist
    }

    # -----------------------------------------------------------------
    # Build uses-graph and identify preamble live-roots.
    #
    # For each file, definitions are sorted by byte offset.  For a reference
    # at byte position P, we binary-search for the largest definition start
    # ≤ P; that definition "contains" the reference and is said to use the
    # referenced entity.
    #
    # References that appear before the first tracked definition (byte
    # position < first def start) are in the file preamble and mark the
    # referenced entity as a live root directly.
    # -----------------------------------------------------------------
    uses: dict[DefKey, set[DefKey]] = {key: set() for key in registry}
    preamble_roots: set[DefKey] = set()

    for lib_path, (defs, refs) in file_data.items():
        # Parallel lists for bisect: byte positions and corresponding keys.
        starts: list[int] = [byte for byte, _ln, _n, _k in defs]
        keys: list[DefKey] = [(lib_path, name) for _byte, _ln, name, _k in defs]

    for lib_path, (defs, refs) in file_data.items():
        # Parallel lists for bisect: byte positions and corresponding keys.
        starts: list[int] = [byte for byte, _ln, _n, _k in defs]
        keys: list[DefKey] = [(lib_path, name) for _byte, _ln, name, _k in defs]

        for ref_byte, ref_lib, ref_name, ref_kind in refs:
            if ref_lib not in local_libs:
                continue  # Stdlib or external project — irrelevant

            target: DefKey = (ref_lib, ref_name)
            if target not in registry:
                # Local variable, auto-generated scheme, inductive type, etc.
                continue

            if ref_kind == "scheme":
                # A `scheme`-kind reference arises from a `Combined Scheme foo
                # from a, b, c` command.  Rocq emits no definition record for
                # the combined scheme itself, so the ingredients (a, b, c) would
                # otherwise appear unreferenced.  Treat such a reference as a
                # live root: if the Combined Scheme command appears anywhere in
                # the file (even inside a definition body), the ingredient is
                # used.
                preamble_roots.add(target)
                continue

            idx = bisect.bisect_right(starts, ref_byte) - 1
            if idx < 0:
                # Before all tracked definitions: preamble reference.
                preamble_roots.add(target)
            else:
                source: DefKey = keys[idx]
                if source != target:    # exclude self-references (recursion)
                    uses[source].add(target)

        # ---------------------------------------------------------------
        # Mutual-lemma with-clauses: "Lemma A ... with B : ..."
        #
        # Rocq does not emit R-line cross-references between the primary and
        # secondary components of a mutual Lemma/Theorem proof, so B would
        # otherwise appear unreferenced even when A is live.
        #
        # Heuristic: scan the .v source for lines of the form
        #   with <name> :  (colon NOT immediately followed by `=`)
        # These mark the secondary component of a mutual-lemma declaration.
        # For each such name that is a tracked `prf` definition, we add an
        # edge: (preceding prf) → (secondary prf), so that if the primary
        # lemma is live its companion is also reachable.
        # ---------------------------------------------------------------
        prf_starts: list[int] = [
            byte for byte, _ln, _n, knd in defs if knd == "prf"
        ]
        prf_keys: list[DefKey] = [
            (lib_path, name) for byte, _ln, name, knd in defs if knd == "prf"
        ]

        v_text = v_texts[lib_path]
        for m in _MUTUAL_LEMMA_WITH_RE.finditer(v_text):
            companion_name = m.group(1)
            companion_key: DefKey = (lib_path, companion_name)
            if companion_key not in registry or registry[companion_key][2] != "prf":
                continue  # Not a tracked prf — Fixpoint/Inductive with-clause

            with_pos = m.start()
            idx2 = bisect.bisect_right(prf_starts, with_pos) - 1
            if idx2 >= 0:
                primary_key = prf_keys[idx2]
                if primary_key != companion_key:
                    uses[primary_key].add(companion_key)

        # ---------------------------------------------------------------
        # Mutual-definition with-clauses: "Scheme/Fixpoint A ... with B :="
        #
        # Secondary components of a "Scheme A := ... with B := ..." block
        # are generated together with A and cannot be separated.  If A is
        # live (e.g. used in a Combined Scheme) then B is structurally live
        # too even when no R-line reference to B exists.
        #
        # Heuristic: scan for "with <name> :=" at the start of a line; if
        # the name is a tracked `def`, add edge (preceding def) → companion.
        # For mutual Fixpoints this is redundant (R-lines already cover it)
        # but harmless.
        # ---------------------------------------------------------------
        def_starts: list[int] = [
            byte for byte, _ln, _n, knd in defs if knd == "def"
        ]
        def_keys: list[DefKey] = [
            (lib_path, name) for byte, _ln, name, knd in defs if knd == "def"
        ]

        for m in _MUTUAL_DEF_WITH_RE.finditer(v_text):
            companion_name = m.group(1)
            companion_key2: DefKey = (lib_path, companion_name)
            if companion_key2 not in registry or registry[companion_key2][2] != "def":
                continue  # Not a tracked def

            with_pos = m.start()
            idx3 = bisect.bisect_right(def_starts, with_pos) - 1
            if idx3 >= 0:
                primary_key2 = def_keys[idx3]
                if primary_key2 != companion_key2:
                    uses[primary_key2].add(companion_key2)

    # -----------------------------------------------------------------
    # BFS from live roots to find all reachable (live) definitions.
    # -----------------------------------------------------------------
    live: set[DefKey] = set(allowlisted) | preamble_roots
    queue: list[DefKey] = list(live)
    while queue:
        current = queue.pop()
        for dep in uses.get(current, ()):
            if dep not in live:
                live.add(dep)
                queue.append(dep)

    # -----------------------------------------------------------------
    # Collect dead definitions and emit verbose output.
    # -----------------------------------------------------------------
    dead: list[tuple[str, int, str, str]] = []
    for key, (fname, line_no, kind) in registry.items():
        _lib, name = key
        label = _KIND_LABEL.get(kind, kind)

        if key in allowlisted:
            if verbose:
                print(f"  {fname}:{line_no}  {label:12s}  {name!r:40s}  (allowlisted)")
            continue

        is_dead = key not in live
        if verbose:
            status = "DEAD" if is_dead else "live"
            print(f"  {fname}:{line_no}  {label:12s}  {name!r:40s}  ({status})")
        if is_dead:
            dead.append((fname, line_no, kind, name))

    return dead


# ---------------------------------------------------------------------------
# CLI  (identical interface to previous versions)
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Find unused Rocq definitions and lemmata (glob-based).",
    )
    parser.add_argument(
        "--coqproject",
        default="_CoqProject",
        metavar="FILE",
        help="Path to _CoqProject (default: _CoqProject)",
    )
    parser.add_argument(
        "--allowlist",
        metavar="FILE",
        help=(
            "Path to a file listing definition names (one per line) that "
            "should not be reported as dead.  Lines starting with '#' and "
            "blank lines are ignored."
        ),
    )
    parser.add_argument(
        "--error-on-dead",
        action="store_true",
        help="Exit with code 1 when unused definitions are found",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Print live/dead status for every tracked definition",
    )
    args = parser.parse_args()

    coqproject = Path(args.coqproject)
    if not coqproject.exists():
        print(f"Error: {coqproject} not found", file=sys.stderr)
        sys.exit(2)

    allowed: set[str] = set()
    if args.allowlist:
        allowlist_path = Path(args.allowlist)
        if not allowlist_path.exists():
            print(f"Error: allowlist {allowlist_path} not found", file=sys.stderr)
            sys.exit(2)
        allowed = read_allowlist(allowlist_path)

    dead = find_dead_code(coqproject, verbose=args.verbose, allowlist=allowed)

    if dead:
        print(f"Found {len(dead)} potentially unused definition(s):\n")
        for fname, line_no, kind, name in sorted(dead):
            print(f"  {fname}:{line_no}: {_KIND_LABEL.get(kind, kind)} {name}")
        print()
        if args.error_on_dead:
            sys.exit(1)
    else:
        print("No unused definitions found.")


if __name__ == "__main__":
    main()
