name: Rocq build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - uses: rrbutani/use-nix-shell-action@v1
        with:
          file: shell.nix

      - name: Build with Rocq
        run: |
          set -eux
          rocq makefile -f _CoqProject -o Makefile && make
